name: Deploy to Firebase
on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.84.3"

      - name: Build Static HTML
        run: hugo

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}